name: cots_2211104024_alfianmutakim
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.6.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: SF Pro Text
      fonts:
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-Regular.otf
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-Medium.otf
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-Semibold.otf
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-Bold.otf
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-BoldItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-Light.otf
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-LightItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-Heavy.otf
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-HeavyItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-MediumItalic.otf
        - asset: assets/fonts/SF-Pro-Text-Font-Family/SF-Pro-Text-SemiboldItalic.otf
  assets:
    - assets/images/
    - assets/icons/
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/gojek.png
    - assets/icons/gopulsa.png
    - assets/icons/goride.png
    - assets/icons/gocar.png
    - assets/icons/gofood.png
    - assets/icons/gosend.png
    - assets/icons/gomart.png
    - assets/icons/goclub.png
    - assets/images/vektor1.png
    - assets/images/vektor2.png
    - assets/images/vektor3.png
    - assets/images/gopay.png
    - assets/icons/topup.png
    - assets/icons/pay.png
    - assets/icons/explore.png
    - assets/icons/home.png
    - assets/icons/promosi.png
    - assets/icons/order.png
    - assets/icons/pesan.png
    - assets/images/background.png
    - assets/icons/cari.png
